### ISSUE TITLE
YOU FUCKING IDIOT

### ISSUE THREAD

**Issue by KDVFirehawk** [Dmy1tro/zoo#13]
FUCK YOU, YOUR MATERIAL.MODULE.TS IS BROKEN, FUCKING DATEPICKER NOT WORKED
MatNativeDateModule MUST BE UPPER THAN MatMomentDateModule IN IMPORTS

I SPENT 1 MONTH TO SOLVE THIS PROBLEM

**Comment by Dmy1tro** [comment]
Ok
